### ISSUE TITLE
async_create_task is not supported after python3.8

### ISSUE THREAD

**Issue by xiandong79** [nardew/cryptoxlib-aio#80]
```
E [2022-06-19 02:52:24,037] Task exception was never retrieved
future: <Task finished name='Task-4' coro=<CryptoXLibClient.start_websockets() done, defined at /home/ubuntu/.local/lib/python3.10/site-packages/cryptoxlib/CryptoXLibClient.py:219> exception=Exception('Unsupported Python version! Only versions 3.6.x, 3.7.x and 3.8.x are supported.')>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cryptoxlib/CryptoXLibClient.py", line 227, in start_websockets
    tasks.append(async_create_task(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/cryptoxlib/version_conversions.py", line 40, in async_create_task
    raise Exception(f'Unsupported Python version! Only versions 3.6.x, 3.7.x and 3.8.x are supported.')
Exception: Unsupported Python version! Only versions 3.6.x, 3.7.x and 3.8.x are supported.
/usr/lib/python3.10/asyncio/base_events.py:1897: RuntimeWarning: coroutine 'WebsocketMgr.run' was never awaited
  handle = None  # Needed to break cycles when an exception occurs.
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by nardew** [comment]
Hi @xiandong79, I assume you are running with python 3.10. I have tested the library only up to python 3.9 (the error message has a mistake and should read 3.9.x) and that's why officially supported it only up to that version. I will run a few more tests for 3.10 and will add into the list of supported versions. If you spotted some other problems, please let me know.

**Comment by nardew** [comment]
@xiandong79 I pushed changes on branch `p310`. When we resolve the issue with aiohttp from the other thread, I will officially deliver it.

**Comment by nardew** [comment]
Delivered in `5.3.0`.
